### ISSUE TITLE
Webcam

### ISSUE THREAD

**Issue by jcheunglin** [YGQ8988/HP-ProBook430G6#2]
打扰一下，问题求助，我笔记本是Elitebook 830 G5，然后camera可以识别，但是没法使用，详细截图在下面，能看出什么问题吗。目前还是小白，不太懂，把你ketx 中的uvc2facetime替换了之后重建缓存还是不能用。
![image](https://user-images.githubusercontent.com/33308725/71593328-85d5ce00-2b6e-11ea-9e5e-53f17d16aec3.png)
![image](https://user-images.githubusercontent.com/33308725/71593331-8d957280-2b6e-11ea-982f-a442550602e1.png)
![image](https://user-images.githubusercontent.com/33308725/71593373-b6b60300-2b6e-11ea-9490-2f7c8b7879bc.png)

**Comment by chwxn** [comment]
我的是g6你用的什么网卡？

**Comment by jcheunglin** [comment]
dw 1820a

**Comment by chwxn** [comment]
> dw 1820a

嗯，430g6 他好像换成白果卡了。

**Comment by tedgo** [comment]
> 我的是g6你用的什么网卡？
请问830 g6可以么？

**Comment by jcheunglin** [comment]
> > 我的是g6你用的什么网卡？
> > 请问830 g6可以么？

应该是可以的 ，网卡是dw1820a，有些问题，黑苹果挺心累的

**Comment by qian-wu** [comment]
830 G6 我用94352蓝牙出不来

**Comment by tedgo** [comment]
@qian-wu 请问下你用的是哪个EFI，方便连驱动给我发一个么？谢谢
