### ISSUE TITLE
我的机型是elitebook 830，我想问下用1820和原生卡有类似白名单的限制吗？ 

### ISSUE THREAD

**Issue by chwxn** [YGQ8988/HP-ProBook430G6#3]

**Comment by jcheunglin** [comment]
惠普18年后的机器貌似无白名单了，可以上，不过1820和1820a是两款不同的吧

**Comment by chwxn** [comment]
> 惠普18年后的机器貌似无白名单了，可以上，不过1820和1820a是两款不同的吧

好的，1820 1820a不一样这个我知道。我看你有维护830g5的clover，你用的1820a？ 正常使用吗？有屏蔽针脚？

**Comment by jcheunglin** [comment]
上面描述清楚了，dw1820a cn-08pkf，无需屏蔽针脚，wifi正常，蓝牙睡眠之后无法连接，最终导致系统崩溃，所以我在bios里面屏蔽了蓝牙。一直保持不休眠是没有问题的，我100快的蓝牙耳机都可以用。蓝牙休眠问题比较头疼

**Comment by chwxn** [comment]
> 上面描述清楚了，dw1820a cn-08pkf，无需屏蔽针脚，wifi正常，蓝牙睡眠之后无法连接，最终导致系统崩溃，所以我在bios里面屏蔽了蓝牙。一直保持不休眠是没有问题的，我100快的蓝牙耳机都可以用。蓝牙休眠问题比较头疼

难怪换了白果卡。

**Comment by chwxn** [comment]
> 上面描述清楚了，dw1820a cn-08pkf，无需屏蔽针脚，wifi正常，蓝牙睡眠之后无法连接，最终导致系统崩溃，所以我在bios里面屏蔽了蓝牙。一直保持不休眠是没有问题的，我100快的蓝牙耳机都可以用。蓝牙休眠问题比较头疼
